[build]
  base = "jwt-auth-frontend"
  command = "npm install && npm run build"
  publish = "jwt-auth-frontend/build"
  functions = "jwt-auth-frontend/netlify/functions"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[functions]
  directory = "jwt-auth-frontend/netlify/functions"
