[build]
  base = "jwt-auth-frontend"
  command = "npm ci && npm run build"
  publish = "build"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
