services:
  - type: web
    name: jwt-auth-backend
    env: node
    rootDir: jwt-auth-backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: RENDER
        value: "true"
    autoDeploy: false
